/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthenticatedCitizenRouteRouteImport } from './routes/_authenticated/citizen/route'
import { Route as AuthenticatedMinistryRouteRouteImport } from './routes/_authenticated/ministry/route'
import { Route as AuthenticatedOfficerRouteRouteImport } from './routes/_authenticated/officer/route'
import { Route as AuthenticatedCitizenIndexRouteImport } from './routes/_authenticated/citizen/index'
import { Route as AuthenticatedCitizenWorkspaceRouteImport } from './routes/_authenticated/citizen/$workspace'
import { Route as AuthenticatedCitizenCaseRouteImport } from './routes/_authenticated/citizen/case'
import { Route as AuthenticatedCitizenCompensationRouteImport } from './routes/_authenticated/citizen/compensation'
import { Route as AuthenticatedCitizenDocumentsRouteImport } from './routes/_authenticated/citizen/documents'
import { Route as AuthenticatedCitizenHearingRouteImport } from './routes/_authenticated/citizen/hearing'
import { Route as AuthenticatedCitizenHelpRouteImport } from './routes/_authenticated/citizen/help'
import { Route as AuthenticatedCitizenNotificationsRouteImport } from './routes/_authenticated/citizen/notifications'
import { Route as AuthenticatedCitizenObjectionsRouteImport } from './routes/_authenticated/citizen/objections'
import { Route as AuthenticatedCitizenPaymentDiscrepancyRouteImport } from './routes/_authenticated/citizen/payment-discrepancy'
import { Route as AuthenticatedCitizenRrRouteImport } from './routes/_authenticated/citizen/rr'
import { Route as AuthenticatedCitizenSmsRouteImport } from './routes/_authenticated/citizen/sms'
import { Route as AuthenticatedCitizenTimelineRouteImport } from './routes/_authenticated/citizen/timeline'
import { Route as AuthenticatedCitizenVerificationRouteImport } from './routes/_authenticated/citizen/verification'
import { Route as AuthenticatedMinistryIndexRouteImport } from './routes/_authenticated/ministry/index'
import { Route as AuthenticatedMinistryWorkspaceRouteImport } from './routes/_authenticated/ministry/$workspace'
import { Route as AuthenticatedOfficerIndexRouteImport } from './routes/_authenticated/officer/index'
import { Route as AuthenticatedOfficerWorkspaceRouteImport } from './routes/_authenticated/officer/$workspace'
import { Route as AuthenticatedOfficerGisRouteImport } from './routes/_authenticated/officer/gis'
import { Route as AuthenticatedOfficerRevenueRouteRouteImport } from './routes/_authenticated/officer/revenue/route'
import { Route as AuthenticatedOfficerRrRouteRouteImport } from './routes/_authenticated/officer/rr/route'
import { Route as AuthenticatedOfficerSurveyRouteRouteImport } from './routes/_authenticated/officer/survey/route'
import { Route as AuthenticatedOfficerTreasuryRouteRouteImport } from './routes/_authenticated/officer/treasury/route'
import { Route as AuthenticatedOfficerRevenueIndexRouteImport } from './routes/_authenticated/officer/revenue/index'
import { Route as AuthenticatedOfficerRevenueCasesRouteImport } from './routes/_authenticated/officer/revenue/cases'
import { Route as AuthenticatedOfficerRevenueNotificationsRouteImport } from './routes/_authenticated/officer/revenue/notifications'
import { Route as AuthenticatedOfficerRevenueObjectionsRouteImport } from './routes/_authenticated/officer/revenue/objections'
import { Route as AuthenticatedOfficerRrIndexRouteImport } from './routes/_authenticated/officer/rr/index'
import { Route as AuthenticatedOfficerRrFamiliesRouteImport } from './routes/_authenticated/officer/rr/families'
import { Route as AuthenticatedOfficerSurveyIndexRouteImport } from './routes/_authenticated/officer/survey/index'
import { Route as AuthenticatedOfficerSurveyIssuesRouteImport } from './routes/_authenticated/officer/survey/issues'
import { Route as AuthenticatedOfficerSurveyParcelsRouteImport } from './routes/_authenticated/officer/survey/parcels'
import { Route as AuthenticatedOfficerTreasuryIndexRouteImport } from './routes/_authenticated/officer/treasury/index'
import { Route as AuthenticatedOfficerTreasuryAwardsRouteImport } from './routes/_authenticated/officer/treasury/awards'
import { Route as AuthenticatedOfficerTreasuryPaymentsRouteImport } from './routes/_authenticated/officer/treasury/payments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCitizenRouteRoute =
  AuthenticatedCitizenRouteRouteImport.update({
    id: '/citizen',
    path: '/citizen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinistryRouteRoute =
  AuthenticatedMinistryRouteRouteImport.update({
    id: '/ministry',
    path: '/ministry',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfficerRouteRoute =
  AuthenticatedOfficerRouteRouteImport.update({
    id: '/officer',
    path: '/officer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCitizenIndexRoute =
  AuthenticatedCitizenIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenWorkspaceRoute =
  AuthenticatedCitizenWorkspaceRouteImport.update({
    id: '/$workspace',
    path: '/$workspace',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenCaseRoute =
  AuthenticatedCitizenCaseRouteImport.update({
    id: '/case',
    path: '/case',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenCompensationRoute =
  AuthenticatedCitizenCompensationRouteImport.update({
    id: '/compensation',
    path: '/compensation',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenDocumentsRoute =
  AuthenticatedCitizenDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenHearingRoute =
  AuthenticatedCitizenHearingRouteImport.update({
    id: '/hearing',
    path: '/hearing',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenHelpRoute =
  AuthenticatedCitizenHelpRouteImport.update({
    id: '/help',
    path: '/help',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenNotificationsRoute =
  AuthenticatedCitizenNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenObjectionsRoute =
  AuthenticatedCitizenObjectionsRouteImport.update({
    id: '/objections',
    path: '/objections',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenPaymentDiscrepancyRoute =
  AuthenticatedCitizenPaymentDiscrepancyRouteImport.update({
    id: '/payment-discrepancy',
    path: '/payment-discrepancy',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenRrRoute = AuthenticatedCitizenRrRouteImport.update({
  id: '/rr',
  path: '/rr',
  getParentRoute: () => AuthenticatedCitizenRouteRoute,
} as any)
const AuthenticatedCitizenSmsRoute = AuthenticatedCitizenSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => AuthenticatedCitizenRouteRoute,
} as any)
const AuthenticatedCitizenTimelineRoute =
  AuthenticatedCitizenTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedCitizenVerificationRoute =
  AuthenticatedCitizenVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedCitizenRouteRoute,
  } as any)
const AuthenticatedMinistryIndexRoute =
  AuthenticatedMinistryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMinistryRouteRoute,
  } as any)
const AuthenticatedMinistryWorkspaceRoute =
  AuthenticatedMinistryWorkspaceRouteImport.update({
    id: '/$workspace',
    path: '/$workspace',
    getParentRoute: () => AuthenticatedMinistryRouteRoute,
  } as any)
const AuthenticatedOfficerIndexRoute =
  AuthenticatedOfficerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerWorkspaceRoute =
  AuthenticatedOfficerWorkspaceRouteImport.update({
    id: '/$workspace',
    path: '/$workspace',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerGisRoute = AuthenticatedOfficerGisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => AuthenticatedOfficerRouteRoute,
} as any)
const AuthenticatedOfficerRevenueRouteRoute =
  AuthenticatedOfficerRevenueRouteRouteImport.update({
    id: '/revenue',
    path: '/revenue',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerRrRouteRoute =
  AuthenticatedOfficerRrRouteRouteImport.update({
    id: '/rr',
    path: '/rr',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerSurveyRouteRoute =
  AuthenticatedOfficerSurveyRouteRouteImport.update({
    id: '/survey',
    path: '/survey',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerTreasuryRouteRoute =
  AuthenticatedOfficerTreasuryRouteRouteImport.update({
    id: '/treasury',
    path: '/treasury',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerRevenueIndexRoute =
  AuthenticatedOfficerRevenueIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOfficerRevenueRouteRoute,
  } as any)
const AuthenticatedOfficerRevenueCasesRoute =
  AuthenticatedOfficerRevenueCasesRouteImport.update({
    id: '/cases',
    path: '/cases',
    getParentRoute: () => AuthenticatedOfficerRevenueRouteRoute,
  } as any)
const AuthenticatedOfficerRevenueNotificationsRoute =
  AuthenticatedOfficerRevenueNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedOfficerRevenueRouteRoute,
  } as any)
const AuthenticatedOfficerRevenueObjectionsRoute =
  AuthenticatedOfficerRevenueObjectionsRouteImport.update({
    id: '/objections',
    path: '/objections',
    getParentRoute: () => AuthenticatedOfficerRevenueRouteRoute,
  } as any)
const AuthenticatedOfficerRrIndexRoute =
  AuthenticatedOfficerRrIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOfficerRrRouteRoute,
  } as any)
const AuthenticatedOfficerRrFamiliesRoute =
  AuthenticatedOfficerRrFamiliesRouteImport.update({
    id: '/families',
    path: '/families',
    getParentRoute: () => AuthenticatedOfficerRrRouteRoute,
  } as any)
const AuthenticatedOfficerSurveyIndexRoute =
  AuthenticatedOfficerSurveyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOfficerSurveyRouteRoute,
  } as any)
const AuthenticatedOfficerSurveyIssuesRoute =
  AuthenticatedOfficerSurveyIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthenticatedOfficerSurveyRouteRoute,
  } as any)
const AuthenticatedOfficerSurveyParcelsRoute =
  AuthenticatedOfficerSurveyParcelsRouteImport.update({
    id: '/parcels',
    path: '/parcels',
    getParentRoute: () => AuthenticatedOfficerSurveyRouteRoute,
  } as any)
const AuthenticatedOfficerTreasuryIndexRoute =
  AuthenticatedOfficerTreasuryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOfficerTreasuryRouteRoute,
  } as any)
const AuthenticatedOfficerTreasuryAwardsRoute =
  AuthenticatedOfficerTreasuryAwardsRouteImport.update({
    id: '/awards',
    path: '/awards',
    getParentRoute: () => AuthenticatedOfficerTreasuryRouteRoute,
  } as any)
const AuthenticatedOfficerTreasuryPaymentsRoute =
  AuthenticatedOfficerTreasuryPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedOfficerTreasuryRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/citizen': typeof AuthenticatedCitizenRouteRouteWithChildren
  '/ministry': typeof AuthenticatedMinistryRouteRouteWithChildren
  '/officer': typeof AuthenticatedOfficerRouteRouteWithChildren
  '/officer/revenue': typeof AuthenticatedOfficerRevenueRouteRouteWithChildren
  '/officer/rr': typeof AuthenticatedOfficerRrRouteRouteWithChildren
  '/officer/survey': typeof AuthenticatedOfficerSurveyRouteRouteWithChildren
  '/officer/treasury': typeof AuthenticatedOfficerTreasuryRouteRouteWithChildren
  '/citizen/$workspace': typeof AuthenticatedCitizenWorkspaceRoute
  '/citizen/case': typeof AuthenticatedCitizenCaseRoute
  '/citizen/compensation': typeof AuthenticatedCitizenCompensationRoute
  '/citizen/documents': typeof AuthenticatedCitizenDocumentsRoute
  '/citizen/hearing': typeof AuthenticatedCitizenHearingRoute
  '/citizen/help': typeof AuthenticatedCitizenHelpRoute
  '/citizen/notifications': typeof AuthenticatedCitizenNotificationsRoute
  '/citizen/objections': typeof AuthenticatedCitizenObjectionsRoute
  '/citizen/payment-discrepancy': typeof AuthenticatedCitizenPaymentDiscrepancyRoute
  '/citizen/rr': typeof AuthenticatedCitizenRrRoute
  '/citizen/sms': typeof AuthenticatedCitizenSmsRoute
  '/citizen/timeline': typeof AuthenticatedCitizenTimelineRoute
  '/citizen/verification': typeof AuthenticatedCitizenVerificationRoute
  '/ministry/$workspace': typeof AuthenticatedMinistryWorkspaceRoute
  '/officer/$workspace': typeof AuthenticatedOfficerWorkspaceRoute
  '/officer/gis': typeof AuthenticatedOfficerGisRoute
  '/citizen/': typeof AuthenticatedCitizenIndexRoute
  '/ministry/': typeof AuthenticatedMinistryIndexRoute
  '/officer/': typeof AuthenticatedOfficerIndexRoute
  '/officer/revenue/cases': typeof AuthenticatedOfficerRevenueCasesRoute
  '/officer/revenue/notifications': typeof AuthenticatedOfficerRevenueNotificationsRoute
  '/officer/revenue/objections': typeof AuthenticatedOfficerRevenueObjectionsRoute
  '/officer/rr/families': typeof AuthenticatedOfficerRrFamiliesRoute
  '/officer/survey/issues': typeof AuthenticatedOfficerSurveyIssuesRoute
  '/officer/survey/parcels': typeof AuthenticatedOfficerSurveyParcelsRoute
  '/officer/treasury/awards': typeof AuthenticatedOfficerTreasuryAwardsRoute
  '/officer/treasury/payments': typeof AuthenticatedOfficerTreasuryPaymentsRoute
  '/officer/revenue/': typeof AuthenticatedOfficerRevenueIndexRoute
  '/officer/rr/': typeof AuthenticatedOfficerRrIndexRoute
  '/officer/survey/': typeof AuthenticatedOfficerSurveyIndexRoute
  '/officer/treasury/': typeof AuthenticatedOfficerTreasuryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/citizen/$workspace': typeof AuthenticatedCitizenWorkspaceRoute
  '/citizen/case': typeof AuthenticatedCitizenCaseRoute
  '/citizen/compensation': typeof AuthenticatedCitizenCompensationRoute
  '/citizen/documents': typeof AuthenticatedCitizenDocumentsRoute
  '/citizen/hearing': typeof AuthenticatedCitizenHearingRoute
  '/citizen/help': typeof AuthenticatedCitizenHelpRoute
  '/citizen/notifications': typeof AuthenticatedCitizenNotificationsRoute
  '/citizen/objections': typeof AuthenticatedCitizenObjectionsRoute
  '/citizen/payment-discrepancy': typeof AuthenticatedCitizenPaymentDiscrepancyRoute
  '/citizen/rr': typeof AuthenticatedCitizenRrRoute
  '/citizen/sms': typeof AuthenticatedCitizenSmsRoute
  '/citizen/timeline': typeof AuthenticatedCitizenTimelineRoute
  '/citizen/verification': typeof AuthenticatedCitizenVerificationRoute
  '/ministry/$workspace': typeof AuthenticatedMinistryWorkspaceRoute
  '/officer/$workspace': typeof AuthenticatedOfficerWorkspaceRoute
  '/officer/gis': typeof AuthenticatedOfficerGisRoute
  '/citizen': typeof AuthenticatedCitizenIndexRoute
  '/ministry': typeof AuthenticatedMinistryIndexRoute
  '/officer': typeof AuthenticatedOfficerIndexRoute
  '/officer/revenue/cases': typeof AuthenticatedOfficerRevenueCasesRoute
  '/officer/revenue/notifications': typeof AuthenticatedOfficerRevenueNotificationsRoute
  '/officer/revenue/objections': typeof AuthenticatedOfficerRevenueObjectionsRoute
  '/officer/rr/families': typeof AuthenticatedOfficerRrFamiliesRoute
  '/officer/survey/issues': typeof AuthenticatedOfficerSurveyIssuesRoute
  '/officer/survey/parcels': typeof AuthenticatedOfficerSurveyParcelsRoute
  '/officer/treasury/awards': typeof AuthenticatedOfficerTreasuryAwardsRoute
  '/officer/treasury/payments': typeof AuthenticatedOfficerTreasuryPaymentsRoute
  '/officer/revenue': typeof AuthenticatedOfficerRevenueIndexRoute
  '/officer/rr': typeof AuthenticatedOfficerRrIndexRoute
  '/officer/survey': typeof AuthenticatedOfficerSurveyIndexRoute
  '/officer/treasury': typeof AuthenticatedOfficerTreasuryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/citizen': typeof AuthenticatedCitizenRouteRouteWithChildren
  '/_authenticated/ministry': typeof AuthenticatedMinistryRouteRouteWithChildren
  '/_authenticated/officer': typeof AuthenticatedOfficerRouteRouteWithChildren
  '/_authenticated/officer/revenue': typeof AuthenticatedOfficerRevenueRouteRouteWithChildren
  '/_authenticated/officer/rr': typeof AuthenticatedOfficerRrRouteRouteWithChildren
  '/_authenticated/officer/survey': typeof AuthenticatedOfficerSurveyRouteRouteWithChildren
  '/_authenticated/officer/treasury': typeof AuthenticatedOfficerTreasuryRouteRouteWithChildren
  '/_authenticated/citizen/$workspace': typeof AuthenticatedCitizenWorkspaceRoute
  '/_authenticated/citizen/case': typeof AuthenticatedCitizenCaseRoute
  '/_authenticated/citizen/compensation': typeof AuthenticatedCitizenCompensationRoute
  '/_authenticated/citizen/documents': typeof AuthenticatedCitizenDocumentsRoute
  '/_authenticated/citizen/hearing': typeof AuthenticatedCitizenHearingRoute
  '/_authenticated/citizen/help': typeof AuthenticatedCitizenHelpRoute
  '/_authenticated/citizen/notifications': typeof AuthenticatedCitizenNotificationsRoute
  '/_authenticated/citizen/objections': typeof AuthenticatedCitizenObjectionsRoute
  '/_authenticated/citizen/payment-discrepancy': typeof AuthenticatedCitizenPaymentDiscrepancyRoute
  '/_authenticated/citizen/rr': typeof AuthenticatedCitizenRrRoute
  '/_authenticated/citizen/sms': typeof AuthenticatedCitizenSmsRoute
  '/_authenticated/citizen/timeline': typeof AuthenticatedCitizenTimelineRoute
  '/_authenticated/citizen/verification': typeof AuthenticatedCitizenVerificationRoute
  '/_authenticated/ministry/$workspace': typeof AuthenticatedMinistryWorkspaceRoute
  '/_authenticated/officer/$workspace': typeof AuthenticatedOfficerWorkspaceRoute
  '/_authenticated/officer/gis': typeof AuthenticatedOfficerGisRoute
  '/_authenticated/citizen/': typeof AuthenticatedCitizenIndexRoute
  '/_authenticated/ministry/': typeof AuthenticatedMinistryIndexRoute
  '/_authenticated/officer/': typeof AuthenticatedOfficerIndexRoute
  '/_authenticated/officer/revenue/cases': typeof AuthenticatedOfficerRevenueCasesRoute
  '/_authenticated/officer/revenue/notifications': typeof AuthenticatedOfficerRevenueNotificationsRoute
  '/_authenticated/officer/revenue/objections': typeof AuthenticatedOfficerRevenueObjectionsRoute
  '/_authenticated/officer/rr/families': typeof AuthenticatedOfficerRrFamiliesRoute
  '/_authenticated/officer/survey/issues': typeof AuthenticatedOfficerSurveyIssuesRoute
  '/_authenticated/officer/survey/parcels': typeof AuthenticatedOfficerSurveyParcelsRoute
  '/_authenticated/officer/treasury/awards': typeof AuthenticatedOfficerTreasuryAwardsRoute
  '/_authenticated/officer/treasury/payments': typeof AuthenticatedOfficerTreasuryPaymentsRoute
  '/_authenticated/officer/revenue/': typeof AuthenticatedOfficerRevenueIndexRoute
  '/_authenticated/officer/rr/': typeof AuthenticatedOfficerRrIndexRoute
  '/_authenticated/officer/survey/': typeof AuthenticatedOfficerSurveyIndexRoute
  '/_authenticated/officer/treasury/': typeof AuthenticatedOfficerTreasuryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/unauthorized'
    | '/citizen'
    | '/ministry'
    | '/officer'
    | '/officer/revenue'
    | '/officer/rr'
    | '/officer/survey'
    | '/officer/treasury'
    | '/citizen/$workspace'
    | '/citizen/case'
    | '/citizen/compensation'
    | '/citizen/documents'
    | '/citizen/hearing'
    | '/citizen/help'
    | '/citizen/notifications'
    | '/citizen/objections'
    | '/citizen/payment-discrepancy'
    | '/citizen/rr'
    | '/citizen/sms'
    | '/citizen/timeline'
    | '/citizen/verification'
    | '/ministry/$workspace'
    | '/officer/$workspace'
    | '/officer/gis'
    | '/citizen/'
    | '/ministry/'
    | '/officer/'
    | '/officer/revenue/cases'
    | '/officer/revenue/notifications'
    | '/officer/revenue/objections'
    | '/officer/rr/families'
    | '/officer/survey/issues'
    | '/officer/survey/parcels'
    | '/officer/treasury/awards'
    | '/officer/treasury/payments'
    | '/officer/revenue/'
    | '/officer/rr/'
    | '/officer/survey/'
    | '/officer/treasury/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/unauthorized'
    | '/citizen/$workspace'
    | '/citizen/case'
    | '/citizen/compensation'
    | '/citizen/documents'
    | '/citizen/hearing'
    | '/citizen/help'
    | '/citizen/notifications'
    | '/citizen/objections'
    | '/citizen/payment-discrepancy'
    | '/citizen/rr'
    | '/citizen/sms'
    | '/citizen/timeline'
    | '/citizen/verification'
    | '/ministry/$workspace'
    | '/officer/$workspace'
    | '/officer/gis'
    | '/citizen'
    | '/ministry'
    | '/officer'
    | '/officer/revenue/cases'
    | '/officer/revenue/notifications'
    | '/officer/revenue/objections'
    | '/officer/rr/families'
    | '/officer/survey/issues'
    | '/officer/survey/parcels'
    | '/officer/treasury/awards'
    | '/officer/treasury/payments'
    | '/officer/revenue'
    | '/officer/rr'
    | '/officer/survey'
    | '/officer/treasury'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/unauthorized'
    | '/_authenticated/citizen'
    | '/_authenticated/ministry'
    | '/_authenticated/officer'
    | '/_authenticated/officer/revenue'
    | '/_authenticated/officer/rr'
    | '/_authenticated/officer/survey'
    | '/_authenticated/officer/treasury'
    | '/_authenticated/citizen/$workspace'
    | '/_authenticated/citizen/case'
    | '/_authenticated/citizen/compensation'
    | '/_authenticated/citizen/documents'
    | '/_authenticated/citizen/hearing'
    | '/_authenticated/citizen/help'
    | '/_authenticated/citizen/notifications'
    | '/_authenticated/citizen/objections'
    | '/_authenticated/citizen/payment-discrepancy'
    | '/_authenticated/citizen/rr'
    | '/_authenticated/citizen/sms'
    | '/_authenticated/citizen/timeline'
    | '/_authenticated/citizen/verification'
    | '/_authenticated/ministry/$workspace'
    | '/_authenticated/officer/$workspace'
    | '/_authenticated/officer/gis'
    | '/_authenticated/citizen/'
    | '/_authenticated/ministry/'
    | '/_authenticated/officer/'
    | '/_authenticated/officer/revenue/cases'
    | '/_authenticated/officer/revenue/notifications'
    | '/_authenticated/officer/revenue/objections'
    | '/_authenticated/officer/rr/families'
    | '/_authenticated/officer/survey/issues'
    | '/_authenticated/officer/survey/parcels'
    | '/_authenticated/officer/treasury/awards'
    | '/_authenticated/officer/treasury/payments'
    | '/_authenticated/officer/revenue/'
    | '/_authenticated/officer/rr/'
    | '/_authenticated/officer/survey/'
    | '/_authenticated/officer/treasury/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/citizen': {
      id: '/_authenticated/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof AuthenticatedCitizenRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ministry': {
      id: '/_authenticated/ministry'
      path: '/ministry'
      fullPath: '/ministry'
      preLoaderRoute: typeof AuthenticatedMinistryRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/officer': {
      id: '/_authenticated/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof AuthenticatedOfficerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizen/': {
      id: '/_authenticated/citizen/'
      path: '/'
      fullPath: '/citizen/'
      preLoaderRoute: typeof AuthenticatedCitizenIndexRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/$workspace': {
      id: '/_authenticated/citizen/$workspace'
      path: '/$workspace'
      fullPath: '/citizen/$workspace'
      preLoaderRoute: typeof AuthenticatedCitizenWorkspaceRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/case': {
      id: '/_authenticated/citizen/case'
      path: '/case'
      fullPath: '/citizen/case'
      preLoaderRoute: typeof AuthenticatedCitizenCaseRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/compensation': {
      id: '/_authenticated/citizen/compensation'
      path: '/compensation'
      fullPath: '/citizen/compensation'
      preLoaderRoute: typeof AuthenticatedCitizenCompensationRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/documents': {
      id: '/_authenticated/citizen/documents'
      path: '/documents'
      fullPath: '/citizen/documents'
      preLoaderRoute: typeof AuthenticatedCitizenDocumentsRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/hearing': {
      id: '/_authenticated/citizen/hearing'
      path: '/hearing'
      fullPath: '/citizen/hearing'
      preLoaderRoute: typeof AuthenticatedCitizenHearingRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/help': {
      id: '/_authenticated/citizen/help'
      path: '/help'
      fullPath: '/citizen/help'
      preLoaderRoute: typeof AuthenticatedCitizenHelpRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/notifications': {
      id: '/_authenticated/citizen/notifications'
      path: '/notifications'
      fullPath: '/citizen/notifications'
      preLoaderRoute: typeof AuthenticatedCitizenNotificationsRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/objections': {
      id: '/_authenticated/citizen/objections'
      path: '/objections'
      fullPath: '/citizen/objections'
      preLoaderRoute: typeof AuthenticatedCitizenObjectionsRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/payment-discrepancy': {
      id: '/_authenticated/citizen/payment-discrepancy'
      path: '/payment-discrepancy'
      fullPath: '/citizen/payment-discrepancy'
      preLoaderRoute: typeof AuthenticatedCitizenPaymentDiscrepancyRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/rr': {
      id: '/_authenticated/citizen/rr'
      path: '/rr'
      fullPath: '/citizen/rr'
      preLoaderRoute: typeof AuthenticatedCitizenRrRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/sms': {
      id: '/_authenticated/citizen/sms'
      path: '/sms'
      fullPath: '/citizen/sms'
      preLoaderRoute: typeof AuthenticatedCitizenSmsRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/timeline': {
      id: '/_authenticated/citizen/timeline'
      path: '/timeline'
      fullPath: '/citizen/timeline'
      preLoaderRoute: typeof AuthenticatedCitizenTimelineRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/citizen/verification': {
      id: '/_authenticated/citizen/verification'
      path: '/verification'
      fullPath: '/citizen/verification'
      preLoaderRoute: typeof AuthenticatedCitizenVerificationRouteImport
      parentRoute: typeof AuthenticatedCitizenRouteRoute
    }
    '/_authenticated/ministry/': {
      id: '/_authenticated/ministry/'
      path: '/'
      fullPath: '/ministry/'
      preLoaderRoute: typeof AuthenticatedMinistryIndexRouteImport
      parentRoute: typeof AuthenticatedMinistryRouteRoute
    }
    '/_authenticated/ministry/$workspace': {
      id: '/_authenticated/ministry/$workspace'
      path: '/$workspace'
      fullPath: '/ministry/$workspace'
      preLoaderRoute: typeof AuthenticatedMinistryWorkspaceRouteImport
      parentRoute: typeof AuthenticatedMinistryRouteRoute
    }
    '/_authenticated/officer/': {
      id: '/_authenticated/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof AuthenticatedOfficerIndexRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/$workspace': {
      id: '/_authenticated/officer/$workspace'
      path: '/$workspace'
      fullPath: '/officer/$workspace'
      preLoaderRoute: typeof AuthenticatedOfficerWorkspaceRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/gis': {
      id: '/_authenticated/officer/gis'
      path: '/gis'
      fullPath: '/officer/gis'
      preLoaderRoute: typeof AuthenticatedOfficerGisRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/revenue': {
      id: '/_authenticated/officer/revenue'
      path: '/revenue'
      fullPath: '/officer/revenue'
      preLoaderRoute: typeof AuthenticatedOfficerRevenueRouteRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/rr': {
      id: '/_authenticated/officer/rr'
      path: '/rr'
      fullPath: '/officer/rr'
      preLoaderRoute: typeof AuthenticatedOfficerRrRouteRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/survey': {
      id: '/_authenticated/officer/survey'
      path: '/survey'
      fullPath: '/officer/survey'
      preLoaderRoute: typeof AuthenticatedOfficerSurveyRouteRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/treasury': {
      id: '/_authenticated/officer/treasury'
      path: '/treasury'
      fullPath: '/officer/treasury'
      preLoaderRoute: typeof AuthenticatedOfficerTreasuryRouteRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/revenue/': {
      id: '/_authenticated/officer/revenue/'
      path: '/'
      fullPath: '/officer/revenue/'
      preLoaderRoute: typeof AuthenticatedOfficerRevenueIndexRouteImport
      parentRoute: typeof AuthenticatedOfficerRevenueRouteRoute
    }
    '/_authenticated/officer/revenue/cases': {
      id: '/_authenticated/officer/revenue/cases'
      path: '/cases'
      fullPath: '/officer/revenue/cases'
      preLoaderRoute: typeof AuthenticatedOfficerRevenueCasesRouteImport
      parentRoute: typeof AuthenticatedOfficerRevenueRouteRoute
    }
    '/_authenticated/officer/revenue/notifications': {
      id: '/_authenticated/officer/revenue/notifications'
      path: '/notifications'
      fullPath: '/officer/revenue/notifications'
      preLoaderRoute: typeof AuthenticatedOfficerRevenueNotificationsRouteImport
      parentRoute: typeof AuthenticatedOfficerRevenueRouteRoute
    }
    '/_authenticated/officer/revenue/objections': {
      id: '/_authenticated/officer/revenue/objections'
      path: '/objections'
      fullPath: '/officer/revenue/objections'
      preLoaderRoute: typeof AuthenticatedOfficerRevenueObjectionsRouteImport
      parentRoute: typeof AuthenticatedOfficerRevenueRouteRoute
    }
    '/_authenticated/officer/rr/': {
      id: '/_authenticated/officer/rr/'
      path: '/'
      fullPath: '/officer/rr/'
      preLoaderRoute: typeof AuthenticatedOfficerRrIndexRouteImport
      parentRoute: typeof AuthenticatedOfficerRrRouteRoute
    }
    '/_authenticated/officer/rr/families': {
      id: '/_authenticated/officer/rr/families'
      path: '/families'
      fullPath: '/officer/rr/families'
      preLoaderRoute: typeof AuthenticatedOfficerRrFamiliesRouteImport
      parentRoute: typeof AuthenticatedOfficerRrRouteRoute
    }
    '/_authenticated/officer/survey/': {
      id: '/_authenticated/officer/survey/'
      path: '/'
      fullPath: '/officer/survey/'
      preLoaderRoute: typeof AuthenticatedOfficerSurveyIndexRouteImport
      parentRoute: typeof AuthenticatedOfficerSurveyRouteRoute
    }
    '/_authenticated/officer/survey/issues': {
      id: '/_authenticated/officer/survey/issues'
      path: '/issues'
      fullPath: '/officer/survey/issues'
      preLoaderRoute: typeof AuthenticatedOfficerSurveyIssuesRouteImport
      parentRoute: typeof AuthenticatedOfficerSurveyRouteRoute
    }
    '/_authenticated/officer/survey/parcels': {
      id: '/_authenticated/officer/survey/parcels'
      path: '/parcels'
      fullPath: '/officer/survey/parcels'
      preLoaderRoute: typeof AuthenticatedOfficerSurveyParcelsRouteImport
      parentRoute: typeof AuthenticatedOfficerSurveyRouteRoute
    }
    '/_authenticated/officer/treasury/': {
      id: '/_authenticated/officer/treasury/'
      path: '/'
      fullPath: '/officer/treasury/'
      preLoaderRoute: typeof AuthenticatedOfficerTreasuryIndexRouteImport
      parentRoute: typeof AuthenticatedOfficerTreasuryRouteRoute
    }
    '/_authenticated/officer/treasury/awards': {
      id: '/_authenticated/officer/treasury/awards'
      path: '/awards'
      fullPath: '/officer/treasury/awards'
      preLoaderRoute: typeof AuthenticatedOfficerTreasuryAwardsRouteImport
      parentRoute: typeof AuthenticatedOfficerTreasuryRouteRoute
    }
    '/_authenticated/officer/treasury/payments': {
      id: '/_authenticated/officer/treasury/payments'
      path: '/payments'
      fullPath: '/officer/treasury/payments'
      preLoaderRoute: typeof AuthenticatedOfficerTreasuryPaymentsRouteImport
      parentRoute: typeof AuthenticatedOfficerTreasuryRouteRoute
    }
  }
}

interface AuthenticatedCitizenRouteRouteChildren {
  AuthenticatedCitizenWorkspaceRoute: typeof AuthenticatedCitizenWorkspaceRoute
  AuthenticatedCitizenCaseRoute: typeof AuthenticatedCitizenCaseRoute
  AuthenticatedCitizenCompensationRoute: typeof AuthenticatedCitizenCompensationRoute
  AuthenticatedCitizenDocumentsRoute: typeof AuthenticatedCitizenDocumentsRoute
  AuthenticatedCitizenHearingRoute: typeof AuthenticatedCitizenHearingRoute
  AuthenticatedCitizenHelpRoute: typeof AuthenticatedCitizenHelpRoute
  AuthenticatedCitizenNotificationsRoute: typeof AuthenticatedCitizenNotificationsRoute
  AuthenticatedCitizenObjectionsRoute: typeof AuthenticatedCitizenObjectionsRoute
  AuthenticatedCitizenPaymentDiscrepancyRoute: typeof AuthenticatedCitizenPaymentDiscrepancyRoute
  AuthenticatedCitizenRrRoute: typeof AuthenticatedCitizenRrRoute
  AuthenticatedCitizenSmsRoute: typeof AuthenticatedCitizenSmsRoute
  AuthenticatedCitizenTimelineRoute: typeof AuthenticatedCitizenTimelineRoute
  AuthenticatedCitizenVerificationRoute: typeof AuthenticatedCitizenVerificationRoute
  AuthenticatedCitizenIndexRoute: typeof AuthenticatedCitizenIndexRoute
}

const AuthenticatedCitizenRouteRouteChildren: AuthenticatedCitizenRouteRouteChildren =
  {
    AuthenticatedCitizenWorkspaceRoute: AuthenticatedCitizenWorkspaceRoute,
    AuthenticatedCitizenCaseRoute: AuthenticatedCitizenCaseRoute,
    AuthenticatedCitizenCompensationRoute:
      AuthenticatedCitizenCompensationRoute,
    AuthenticatedCitizenDocumentsRoute: AuthenticatedCitizenDocumentsRoute,
    AuthenticatedCitizenHearingRoute: AuthenticatedCitizenHearingRoute,
    AuthenticatedCitizenHelpRoute: AuthenticatedCitizenHelpRoute,
    AuthenticatedCitizenNotificationsRoute:
      AuthenticatedCitizenNotificationsRoute,
    AuthenticatedCitizenObjectionsRoute: AuthenticatedCitizenObjectionsRoute,
    AuthenticatedCitizenPaymentDiscrepancyRoute:
      AuthenticatedCitizenPaymentDiscrepancyRoute,
    AuthenticatedCitizenRrRoute: AuthenticatedCitizenRrRoute,
    AuthenticatedCitizenSmsRoute: AuthenticatedCitizenSmsRoute,
    AuthenticatedCitizenTimelineRoute: AuthenticatedCitizenTimelineRoute,
    AuthenticatedCitizenVerificationRoute:
      AuthenticatedCitizenVerificationRoute,
    AuthenticatedCitizenIndexRoute: AuthenticatedCitizenIndexRoute,
  }

const AuthenticatedCitizenRouteRouteWithChildren =
  AuthenticatedCitizenRouteRoute._addFileChildren(
    AuthenticatedCitizenRouteRouteChildren,
  )

interface AuthenticatedMinistryRouteRouteChildren {
  AuthenticatedMinistryWorkspaceRoute: typeof AuthenticatedMinistryWorkspaceRoute
  AuthenticatedMinistryIndexRoute: typeof AuthenticatedMinistryIndexRoute
}

const AuthenticatedMinistryRouteRouteChildren: AuthenticatedMinistryRouteRouteChildren =
  {
    AuthenticatedMinistryWorkspaceRoute: AuthenticatedMinistryWorkspaceRoute,
    AuthenticatedMinistryIndexRoute: AuthenticatedMinistryIndexRoute,
  }

const AuthenticatedMinistryRouteRouteWithChildren =
  AuthenticatedMinistryRouteRoute._addFileChildren(
    AuthenticatedMinistryRouteRouteChildren,
  )

interface AuthenticatedOfficerRevenueRouteRouteChildren {
  AuthenticatedOfficerRevenueCasesRoute: typeof AuthenticatedOfficerRevenueCasesRoute
  AuthenticatedOfficerRevenueNotificationsRoute: typeof AuthenticatedOfficerRevenueNotificationsRoute
  AuthenticatedOfficerRevenueObjectionsRoute: typeof AuthenticatedOfficerRevenueObjectionsRoute
  AuthenticatedOfficerRevenueIndexRoute: typeof AuthenticatedOfficerRevenueIndexRoute
}

const AuthenticatedOfficerRevenueRouteRouteChildren: AuthenticatedOfficerRevenueRouteRouteChildren =
  {
    AuthenticatedOfficerRevenueCasesRoute:
      AuthenticatedOfficerRevenueCasesRoute,
    AuthenticatedOfficerRevenueNotificationsRoute:
      AuthenticatedOfficerRevenueNotificationsRoute,
    AuthenticatedOfficerRevenueObjectionsRoute:
      AuthenticatedOfficerRevenueObjectionsRoute,
    AuthenticatedOfficerRevenueIndexRoute:
      AuthenticatedOfficerRevenueIndexRoute,
  }

const AuthenticatedOfficerRevenueRouteRouteWithChildren =
  AuthenticatedOfficerRevenueRouteRoute._addFileChildren(
    AuthenticatedOfficerRevenueRouteRouteChildren,
  )

interface AuthenticatedOfficerRrRouteRouteChildren {
  AuthenticatedOfficerRrFamiliesRoute: typeof AuthenticatedOfficerRrFamiliesRoute
  AuthenticatedOfficerRrIndexRoute: typeof AuthenticatedOfficerRrIndexRoute
}

const AuthenticatedOfficerRrRouteRouteChildren: AuthenticatedOfficerRrRouteRouteChildren =
  {
    AuthenticatedOfficerRrFamiliesRoute: AuthenticatedOfficerRrFamiliesRoute,
    AuthenticatedOfficerRrIndexRoute: AuthenticatedOfficerRrIndexRoute,
  }

const AuthenticatedOfficerRrRouteRouteWithChildren =
  AuthenticatedOfficerRrRouteRoute._addFileChildren(
    AuthenticatedOfficerRrRouteRouteChildren,
  )

interface AuthenticatedOfficerSurveyRouteRouteChildren {
  AuthenticatedOfficerSurveyIssuesRoute: typeof AuthenticatedOfficerSurveyIssuesRoute
  AuthenticatedOfficerSurveyParcelsRoute: typeof AuthenticatedOfficerSurveyParcelsRoute
  AuthenticatedOfficerSurveyIndexRoute: typeof AuthenticatedOfficerSurveyIndexRoute
}

const AuthenticatedOfficerSurveyRouteRouteChildren: AuthenticatedOfficerSurveyRouteRouteChildren =
  {
    AuthenticatedOfficerSurveyIssuesRoute:
      AuthenticatedOfficerSurveyIssuesRoute,
    AuthenticatedOfficerSurveyParcelsRoute:
      AuthenticatedOfficerSurveyParcelsRoute,
    AuthenticatedOfficerSurveyIndexRoute: AuthenticatedOfficerSurveyIndexRoute,
  }

const AuthenticatedOfficerSurveyRouteRouteWithChildren =
  AuthenticatedOfficerSurveyRouteRoute._addFileChildren(
    AuthenticatedOfficerSurveyRouteRouteChildren,
  )

interface AuthenticatedOfficerTreasuryRouteRouteChildren {
  AuthenticatedOfficerTreasuryAwardsRoute: typeof AuthenticatedOfficerTreasuryAwardsRoute
  AuthenticatedOfficerTreasuryPaymentsRoute: typeof AuthenticatedOfficerTreasuryPaymentsRoute
  AuthenticatedOfficerTreasuryIndexRoute: typeof AuthenticatedOfficerTreasuryIndexRoute
}

const AuthenticatedOfficerTreasuryRouteRouteChildren: AuthenticatedOfficerTreasuryRouteRouteChildren =
  {
    AuthenticatedOfficerTreasuryAwardsRoute:
      AuthenticatedOfficerTreasuryAwardsRoute,
    AuthenticatedOfficerTreasuryPaymentsRoute:
      AuthenticatedOfficerTreasuryPaymentsRoute,
    AuthenticatedOfficerTreasuryIndexRoute:
      AuthenticatedOfficerTreasuryIndexRoute,
  }

const AuthenticatedOfficerTreasuryRouteRouteWithChildren =
  AuthenticatedOfficerTreasuryRouteRoute._addFileChildren(
    AuthenticatedOfficerTreasuryRouteRouteChildren,
  )

interface AuthenticatedOfficerRouteRouteChildren {
  AuthenticatedOfficerRevenueRouteRoute: typeof AuthenticatedOfficerRevenueRouteRouteWithChildren
  AuthenticatedOfficerRrRouteRoute: typeof AuthenticatedOfficerRrRouteRouteWithChildren
  AuthenticatedOfficerSurveyRouteRoute: typeof AuthenticatedOfficerSurveyRouteRouteWithChildren
  AuthenticatedOfficerTreasuryRouteRoute: typeof AuthenticatedOfficerTreasuryRouteRouteWithChildren
  AuthenticatedOfficerWorkspaceRoute: typeof AuthenticatedOfficerWorkspaceRoute
  AuthenticatedOfficerGisRoute: typeof AuthenticatedOfficerGisRoute
  AuthenticatedOfficerIndexRoute: typeof AuthenticatedOfficerIndexRoute
}

const AuthenticatedOfficerRouteRouteChildren: AuthenticatedOfficerRouteRouteChildren =
  {
    AuthenticatedOfficerRevenueRouteRoute:
      AuthenticatedOfficerRevenueRouteRouteWithChildren,
    AuthenticatedOfficerRrRouteRoute:
      AuthenticatedOfficerRrRouteRouteWithChildren,
    AuthenticatedOfficerSurveyRouteRoute:
      AuthenticatedOfficerSurveyRouteRouteWithChildren,
    AuthenticatedOfficerTreasuryRouteRoute:
      AuthenticatedOfficerTreasuryRouteRouteWithChildren,
    AuthenticatedOfficerWorkspaceRoute: AuthenticatedOfficerWorkspaceRoute,
    AuthenticatedOfficerGisRoute: AuthenticatedOfficerGisRoute,
    AuthenticatedOfficerIndexRoute: AuthenticatedOfficerIndexRoute,
  }

const AuthenticatedOfficerRouteRouteWithChildren =
  AuthenticatedOfficerRouteRoute._addFileChildren(
    AuthenticatedOfficerRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCitizenRouteRoute: typeof AuthenticatedCitizenRouteRouteWithChildren
  AuthenticatedMinistryRouteRoute: typeof AuthenticatedMinistryRouteRouteWithChildren
  AuthenticatedOfficerRouteRoute: typeof AuthenticatedOfficerRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCitizenRouteRoute: AuthenticatedCitizenRouteRouteWithChildren,
  AuthenticatedMinistryRouteRoute: AuthenticatedMinistryRouteRouteWithChildren,
  AuthenticatedOfficerRouteRoute: AuthenticatedOfficerRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
